### ISSUE TITLE
Accessing service IPs from nodes (uncontained) fails in some setups

### ISSUE THREAD

**Issue by danderson** [danderson/metallb#258]
There have been multiple reports of being unable to reach a service IP when dialing out from a node in the cluster (i.e. not within a container). I was unable to reproduce this originally, but multiple independent reports suggests this may be a bug in a particular version of k8s, or interaction with a specific network addon.

Setups where this has appeared:

- k8s=1.9.3, network_addon=canal, protocol=bgp 
- k8s=1.9.5, network_addon=calico, protocol=bgp

A known workaround is to add the following rule to iptables, in addition to those generated by kube-proxy and the network addon:

```
iptables -A OUTPUT -t nat -d <your pool cidr> -m mark --mark 0x8000 -j MARK --set-xmark 0x0 -m comment --comment "Ensuring K8s nodes can reach MetalLB-announced service IPs. WORKAROUND"
```

This strongly suggests a bug in kube-proxy, since iirc it's the one that uses mark+action to do a bunch of policy decisions.

Next steps: attempt to reproduce this, trace iptables, file upstream bug.

**Comment by danderson** [comment]
Further data: the failing services all use `externalTrafficPolicy: Local`. I suspect this is kube-proxy confusing locally originated and externally originated traffic, and applying the "must blackhole if no local pods" semantics to locally originated traffic (incorrectly).

If I'm right, this should be an easy upstream bug to fix. Still need to repro and investigate more.

**Comment by zakharovvi** [comment]
Hello @danderson !

I can reproduce the issue with k8s=1.9.7, network_addon=calico, protocol=bgp

I can't access to ingress-nginx service "type: LoadBalancer" + "externalTrafficPolicy: Local" from nodes where ingress-nginx pods not launched

How can I help with this issue?

**Comment by kmorning** [comment]
I also have this problem.

k8s=1.13.1, network_addon=weave, protocol=l2
externalTrafficePolicy: Local on service

I can reach the service IP from the node where it's corresponding pod is running, but not from any other node in the cluster, which seems to support the "must blackhole if no local pods" being applied incorrectly.

**Comment by jpiper** [comment]
I had a discussion on the kubernetes repo and the gist is that [this is intended behaviour](https://github.com/kubernetes/kubernetes/issues/75262#issuecomment-471773726)

> this behaviour is expected. Local only traffic should be blackholed if there are no endpoints on that node

**Comment by jpiper** [comment]
I managed to come up with a shitty hack for this (for IPVS).

I added this code [here](https://github.com/kubernetes/kubernetes/blob/v1.14.1/pkg/proxy/ipvs/proxier.go#L1582)

```go
if len(newEndpoints) == 0 && onlyNodeLocalEndpoints {
	for _, epInfo := range proxier.endpointsMap[svcPortName] {
		newEndpoints.Insert(epInfo.String())
	}
}
```

This means LBs with 'externalTrafficPolicy: Local' will still only have BGP advertised on nodes where there is a local endpoint, and on nodes where there isn't a local endpoint, kube-proxy will set up IPVS to point to them endpoints.

This effectively makes kube-proxy use 'externalTrafficPolicy: Local' mode on nodes that have a local endpoint, and `externalTrafficPolicy: Cluster` on all other nodes. However, depending on the setup, it could be preferable to remove the whole IPVS entry completely and have the network stack deal with routing. Not sure how to do this and don't want to get into a rabbit-hole!

**Comment by ffilippopoulos** [comment]
looks like this https://github.com/kubernetes/kubernetes/pull/77523 might be resolving the issue as it allows traffic from nodes to lbs.
I just tested upgrading kube-proxy to `k8s.gcr.io/kube-proxy:v1.15.0-rc.1` that includes it and from the first tests it looks it is solving the issue for me.

**Comment by danderson** [comment]
Nice find @ffilippopoulos !

Closing this bug, since it's "broken as intended" before k8s 1.15 and fixed in k8s 1.15, so there's nothing for MetalLB to do here.

**Comment by salanki** [comment]
This still seems broken in 1.15 with `kube-proxy` in IPVS mode. It seems to me as kubernetes/kubernetes#77523 only fixed it in iptables mode? That seems inconsistent.

**Comment by hightoxicity** [comment]
I understand why @jpiper fix is doing the job, forcing endpoints generation and acting the same way as clusterIP on nodes not running the workloads but It should work even better if no virtual server was created at all for services with externalTrafficPolicy: Local, this way, BGP routing would do its job properly...

**Comment by salanki** [comment]
Does anyone know if `kube-router` in IPVS mode also has this problem?

**Comment by MatthiasLohr** [comment]
I'm currently experiencing something similar. But it's not bound to `externalTrafficPolicy: Local`, I have `Cluster` configured. Kubernetes v1.16.3 deployed with Kubespray, MetalLB with L2. iptables workaround does not work. Any idea?

**Comment by vitobotta** [comment]
Hi @MatthiasLohr I'm having the same problem with the same version of Kubernetes deployed with Rancher. Have you found a solution in the meantime?

**Comment by MatthiasLohr** [comment]
@vitobotta, for exactly this issue unfortunately no. But I found an issue, which looks quite similar to this one, when having multiple NICs configured (and MetalLB and default gateway NICs are different). This it not part of this issue, but the symptoms look like exactly the same. Feel free to concact me (directly or in a new ticket) when having trouble with a multiple NIC configuration.

**Comment by vitobotta** [comment]
Hi @MatthiasLohr , I ended up using Cloudflare's load balancing service since it's cheap and I was anyway using Cloudflare already.
