### ISSUE TITLE
Kubespray+Istio+MetalLB somehow crashes the whole cluster

### ISSUE THREAD

**Issue by danderson** [danderson/metallb#262]
This is a mysterious one, but two people have separately discovered the same thing: if they install a cluster using Kubespray, with Istio enabled, and then install MetalLB, the whole cluster falls over. As in: apiserver is unreachable (possible crashlooping), and _the machines stop accepting new ssh connections_ even though sshd is still up.

I have **no** idea what could possibly be happening. MetalLB does some interesting things to the network, sure, but from a k8s perspective it's just a couple of pods with very vanilla behaviors. How does the mere act of installing them (with no configuration, i.e. MetalLB is doing _nothing_) cause the cluster to go down?

I've played with MetalLB and Istio on a kubeadm-based cluster before, so it seems to be specific to the triplet of kubespray+istio+metallb, and only that triplet. kubespray+istio seems to work, as does kubespray+metallb.

Filing to track this, but I really need a reproduction where I can be ssh'd into the master machine to figure out wth happened.

**Comment by nrobert13** [comment]
The latest kubespray supports istios 0.2.6, which is almost 1 year old. the current one is 0.8.0. does it really make sense to debug something that old. It would maybe make sense to try installing the cluster with kubespray using istio disabled, and use the installation provided by istio to deploy the latest version, and see if it still breaks...

**Comment by inevity** [comment]
Any progress？

**Comment by danderson** [comment]
No progress. I don't use kubespray myself, and I don't have time to debug every cluster bootstrapping tool out there. Additionally, as @nrobert13 points out, kubespray is using a very old version of Istio, so this is quite low on my priority list.

If someone else can debug the problem and offer a solution, I'm happy to implement fixes or take PRs.

**Comment by bjornryden** [comment]
Istio has been removed from Kubespray, so I guess this ticket can be closed.
