### ISSUE TITLE
ExternalTrafficPolicy:Local issues

### ISSUE THREAD

**Issue by luzhongming** [danderson/metallb#263]
**Is this a bug report or a feature request?**:
bug

**What happened**:
Two issues:
1. create a service with local externalPolicy,every thing works fine. After I migrate the Only Pod as the service endpoint to another node,then could not access the service through serviceIP+Port. I think the problem is that the kube-proxy on the second node doesnot update the iptables rules for that serviceIP

2. Create a service with Cluster externalPolicy,then edit the service with Local externalPolicy but the serviceIP nexthop remains allNodes,in another world--the routes for the serviceIP not updated  

**What you expected to happen**:
issue1: second node's kube-proxy should be triggered to update iptables rules

issue2: after Service switchingfrom Cluster to Local externalPolicy, the serviceIP routes should be updated to specific nodes 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version: 0.6.2
- Kubernetes version: 1.9.7
- BGP router type/version: eBGP
- OS (e.g. from /etc/os-release): CentOS7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.21.1.el7.x86_64

**Comment by danderson** [comment]
Both of these scenarios work fine on my clusters. MetalLB does respect the Local traffic policy and updates its announcements, and kube-proxy updates iptables as well.

For both scenarios, please paste your MetalLB configuration, the service definition, the event log for the service, and the routes seen by your BGP router:

- `kubectl get configmap -n metallb-system config -oyaml`
- `kubectl get service <your-service-name> -oyaml`
- `kubectl describe service <your-service-name> -oyaml`
- Whatever the command to dump BGP routes is on your router, e.g. `show ip bgp route` or something.

**Comment by luzhongming** [comment]
Sorry for my description misleading. The actual problem i am facing is that when i create and delete a service with a single pod as its endpoint, the routes for the serviceIP updated properly. BUT,when creating a service with sets of Pods as its endpoints,the routes adding working fine but after i delete the service  the routes for the serviceIP remains on the routers.Please find the info belowing:

1.my metallb configMap
  apiVersion: v1
data:
  config: |
    peers:
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.134
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.134]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.135
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.135]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.136
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.136]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.137
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.137]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.138
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.138]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.139
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.139]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.140
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.140]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.141
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.141]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.142
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.142]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.143
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.143]
    - peer-address: 172.31.10.62
      peer-asn: 65010
      my-asn: 65310
      router-id: 10.10.113.144
      node-selectors:
      - match-expressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [10.10.113.144]
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.10.240.0/22
      avoid-buggy-ips: true
kind: ConfigMap
2. Single Pod endpoint service snapshot
 **kubectl get svc -oymal**
![1000](https://user-images.githubusercontent.com/29879821/40399674-4d56a458-5e71-11e8-8031-b1f37af82b25.png)

**kubectl describe svc**
![image](https://user-images.githubusercontent.com/29879821/40399690-6519d330-5e71-11e8-8af9-09bb71dc62cd.png)
**routes info for 10.10.240.100 on routers**
![image](https://user-images.githubusercontent.com/29879821/40399708-7b354370-5e71-11e8-9b07-f21f54407c38.png)
**After service deletion**
metallb speaker logs:
{"caller":"main.go:264","event":"serviceWithdrawn","ip":"","msg":"withdrawing service announcement","reason":"serviceDeleted","service":"default/luzm1000","ts":"2018-05-23T01:36:31.118967462Z"}
routes info for 10.10.240.100 gone as expected
![image](https://user-images.githubusercontent.com/29879821/40399753-bbfce37c-5e71-11e8-9542-062c612df7e3.png)

3. 3 Pods endpoints Service snapshot
service config info:
![image](https://user-images.githubusercontent.com/29879821/40399776-d37e650c-5e71-11e8-9da6-60fced9b8b88.png)

describe info,3 pods as its endpoints:
![image](https://user-images.githubusercontent.com/29879821/40399812-f1d599c6-5e71-11e8-83a7-9fb0c40fa754.png)

routes info for 10.10.240.100 ,3 nexthop as expected
![image](https://user-images.githubusercontent.com/29879821/40399834-08c70c14-5e72-11e8-907e-14aa47810be9.png)

after service deletion,confirmed no serviceIP 10.10.240.100 used
![image](https://user-images.githubusercontent.com/29879821/40399881-3a02c3c2-5e72-11e8-8554-670fc6aaffab.png)

speaker logs：
{"caller":"main.go:264","event":"serviceWithdrawn","ip":"","msg":"withdrawing service announcement","reason":"serviceDeleted","service":"cattle-system/cattle-service-http","ts":"2018-05-23T01:47:18.032850819Z"}
{"caller":"main.go:264","event":"serviceWithdrawn","ip":"","msg":"withdrawing service announcement","reason":"serviceDeleted","service":"cattle-system/cattle-service-https","ts":"2018-05-23T01:47:18.142403332Z"}

**BUT routes for 10.10.240.100 remains on routers!!!!** even wait for an hour 
![image](https://user-images.githubusercontent.com/29879821/40399933-75aaaae8-5e72-11e8-8c39-1a63427ac5ae.png)

**Comment by danderson** [comment]
Fixed in the linked bug, will be in 0.8.
