### ISSUE TITLE
Implement unnumbered BGP

### ISSUE THREAD

**Issue by aojea** [danderson/metallb#379]
**Is this a bug report or a feature request?**:

Feature request

**What happened**:

Configuring BGP can be tedious if you have a big number of peers, it will be great to make it easier and simpler.

**What you expected to happen**:

It will be great to implement BGP unnumbered to facilitate the configuration

Ref:
https://blog.ipspace.net/2015/02/bgp-configuration-made-simple-with.html
https://marcelwiget.blog/2018/06/21/bgp-over-unnumbered-interfaces-automated/
https://github.com/osrg/gobgp/blob/master/docs/sources/unnumbered-bgp.md

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Can you assign it to me? 
I've planned to work on this soon

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by danderson** [comment]
This depends on IPv6 support, which is currently not great in MetalLB. In particular, it requires full BGP-MP support so we can advertise IPv4 routes over an IPv6 link-local BGP session.

It's all possible, just requires some small tweaks to the BGP libraries.

**Comment by aojea** [comment]
unfortunately, I can't work on this since my priorities changed
