### ISSUE TITLE
Weave's default configuration is broken with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by davidq2q** [danderson/metallb#380]
**Is this a bug report or a feature request?**:
Bug report

**What happened**:
Need source IP address as one of my containers require that information. So switched the externalTrafficPolicy from cluster to local in my service definition. Unfortunately the service stops working. When using curl internally in the overlay network the service works. Just the IP address bound to it and announced by metallb does not work in local mode.

**What you expected to happen**:
Get the real source IP in my service when accessing the loadBalancer IP assigned by metallb.

**How to reproduce it (as minimally and precisely as possible)**:
Run a service then switch externalTrafficPolicy from cluster to local

**Anything else we need to know?**:

**Environment**:
- MetalLB version: 0.8.3
- Kubernetes version: v1.13.1
- BGP router type/version: Layer2
- OS (e.g. from /etc/os-release): Debian 9 (stretch)
- Kernel (e.g. `uname -a`): Linux master1 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by davidq2q** [comment]
Am using kube-proxy mode iptables so it's not related to https://github.com/kubernetes/kubernetes/issues/71596

**Comment by davidq2q** [comment]
When switching kube-proxy to userspace mode externalTrafficPolicy: "Local" returns a result but the real source ip is still from a internal node.

**Comment by davidq2q** [comment]
Fixed this issue by switching kube-proxy mode to ipvs.

**Comment by SeanChristopherConway** [comment]
@davidq2q https://metallb.universe.tf/installation/network-addons/ States that metallb and ipvs mode are not compatible.

**Comment by schaze** [comment]
@davidq2q can you explain what the kube-proxy problem was? 
I am too using metallb and I am not getting external IPs for connections inside container even though I have externalTrafficPolicy set to local. Using Weave as plugin and Layer2. Tried IP Tables and IPVS. Both with the same result.

**Comment by schaze** [comment]
Ok, so after searching for a solution for months I of course have to find it an hour after posting a comment here. Problem was with weave net, one needs to set NO_MASQ_LOCAL to one... See here
https://github.com/weaveworks/weave/issues/2924#issuecomment-407827430 for anyone with the same problem...

**Comment by davidq2q** [comment]
Am running flannel now for 30 days in ipvs modus without issues. But I'll check weave again when provisioning a new server.

**Comment by danderson** [comment]
Sounds like Weave is broken in its default configuration. Not surprising since there's no Kubernetes conformance tests for load-balancing, so everyone is free to ship bugs and only end-users notice.

Reworded title as a documentation bug.

**Comment by carlosedp** [comment]
Exactly, to have Weave expose the source IP you need to deploy it with:

`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.NO_MASQ_LOCAL=1"`

Or add `NO_MASQ_LOCAL=1` to the current deployed Weave.

**Comment by danderson** [comment]
Documented in the website version that'll go live with the next release.
