### ISSUE TITLE
Layer2 mode on k8s VMs(private cloud) don't work loadbalancer.

### ISSUE THREAD

**Issue by juhoson1129** [danderson/metallb#419]
Layer2 mode on k8s VMs(private cloud) don't work loadbalancer.

Hi.

I have some issue.
Issue is that i can't access loadbalancer external_ip.

I am using k8s cluster on my company private cloud vms.
I install metalLB(Layer 2 mode). 
 - service ip pool : 10.166.99.10-10.66.99.240
 - k8s cluster ip pool : 10.166.81.100-10.166.81.120
I followed Layer2 tutorial.(Of course, I changed address-pool value)
I checked all metal-lb pods are running. And speaker log is here.

{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"kube-system/guard","ts":"2019-03-29T03:04:10.595560889Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"kube-system/guard","ts":"2019-03-29T03:04:10.595690374Z"}
{"caller":"arp.go:102","interface":"weave","ip":"10.166.99.10","msg":"got ARP request for service IP, sending response","responseMAC":"12:15:67:ea:f5:c2","senderIP":"10.166.99.10","senderMAC":"2a:52:65:fb:ec:d0","ts":"2019-03-29T03:00:18.182095292Z"}

IDC Network Engineer said.'I think metallb container will send service_ip info to switch. But any arp is not.'
I do not know what part I missed.

addition question : Is metalLB unusable in a private cloud environment?

my environment
 - MetalLB version : 0.7.3
 - kubernetes version : v1.13.2
 - network addon : weave
 - mode : kube-proxy

**Comment by jlcox1970** [comment]
I too had the same issue and have been tracking it down for days...
turns out that MetalLB 0.7.2 works ( I am using shared IP TCP/UDP balancers )
I have tested 07.3 controller with 0.7.2 speaker and it works but highly unrecommended

My guess is that the speaker now wont do ARP on an IP if the NDP responder fails. 
this make IPv4 depend on IPv6 working

**Comment by byronmccollum** [comment]
Having strange issue with 0.7.3, where only 1 IP in my pool wouldn't work. Downgraded to 0.7.2 and things started working.

**Comment by adamelliotfields** [comment]
> this make IPv4 depend on IPv6 working

Thanks @jlcox1970 , this might be the only explanation to my issue.

Kubeadm w/ Cilium and Metallb works fine on DigitalOcean, but not on Lightsail (no IPv6).

**Comment by danderson** [comment]
The IPv4 and IPv6 responders are independent, and don't interfere with each other. Whatever's happening, I don't think it's that. I run MetalLB myself on a v4-only network, and it works fine.

**Comment by adamelliotfields** [comment]
Thanks Dave, I actually resolved my issue.

I was giving Metallb a pool of public IPs, but on EC2, the default interface uses the private IP of the instance (on DigitalOcean, it's the public IP).

The public IP is NAT'd to the private IP. Giving Metallb the private IPs worked.

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
