### ISSUE TITLE
docs update: resilient ecmp in bgp mode

### ISSUE THREAD

**Issue by networkop** [danderson/metallb#420]
BGP mode mentions ECMP limitations of existing switches/routers. One way this problem could be (partially) mitigated is by using resilient ECMP (supported by most of the major network vendors). Perhaps it's worth mentioning that in the "mitigation strategies" section. I'm happy to do a pull request for this.

**Comment by danderson** [comment]
Oh neat, I didn't know about this. I'll add a quick note in the docs.
