### ISSUE TITLE
Document and e2e the best practices of BIRD as a frontend to MLB

### ISSUE THREAD

**Issue by briantopping** [danderson/metallb#424]
I've been spending some time recently in a configuration where [BIRD](https://bird.network.cz) is running at the host level for a Kubernetes node. BIRD is BGP peered with the MLB speaker on the node and everything should be good for [all the protocols BIRD supports](https://bird.network.cz/?get_doc&v=20&f=bird-6.html). 

What strikes me in reading that page is all the things that we don't want to implement. #256 is a good example of something that makes all the sense in the world, but what comes next? Will things like signing get handled well?

Combined with #423, I am currently using the following BIRD configuration to peer on the same node:
```
protocol bgp bgp_metal_mynode {
        local as MYASN;
        neighbor 10.10.0.41 as MYASN; # this is the address of the eno2 interface noted below
        passive yes;
        ipv4 {
                preference 300;
                next hop self;
                import filter {
                        bgp_origin = ORIGIN_IGP;
                        ifname = "eno2"; # noted above, but it's not exactly *working*...
                        accept;
                };
                export none;
        };
}
```
One of the things that is not working here is BIRD wants to report the node as `unreachable`, presumably because it does not see the pool addresses on any interface. I have tried several configurations and filters in BIRD, but haven't had complete success where MLB in Cluster mode could propagate `/32` addresses and all nodes (including the host itself) can reach them without sunk traffic. 

Last point here may be a separate issue: Once e2e is working well, setting up a BIRD test might be a good idea, if for nothing else other than working and refactorable reference.

**Comment by danderson** [comment]
I think this would be a great blog post, but I think this will just confuse things in documentation. MetalLB is deliberately not a kitchen sink of every possible protocol and config option, and "peer with a fancy router and do fancy router things there" is working as intended for advanced users. But from what I see in MetalLB support requests, trying to provide a one size fits all advanced BGP setup will just lead to more requests for help :(

**Comment by briantopping** [comment]
Well, it's documented here in case anyone were truly looking for a solution.. :)
