### ISSUE TITLE
Metallb in l2 mode should publish an event indicating which node is advertising a vip.

### ISSUE THREAD

**Issue by mauilion** [danderson/metallb#430]
Feature Request:

in L2 mode it would help to understand what node is servicing a given vip. 
Ideally, the speaker could publish an event to the service object indicating the node that has "won" the election for a given vip. 

If we need to move to another node a new event should be published to that service object. So that we can understand that the ip is now served by a different speaker. 

This is helpful when trying to understand how l2 mode will interact with the underlying network.

**Comment by mauilion** [comment]
This could also help to isolate issues where in l2 mode arp is taking longer to timeout on re election :)

**Comment by zetaab** [comment]
What kind of event you mean? There is already one log message coming when the ip address is active in speaker: https://github.com/danderson/metallb/blob/master/speaker/main.go#L229

it looks like:
```
{"caller":"main.go:229","event":"serviceAnnounced","ip":"10.1.0.31","msg":"service has IP, announcing","pool":"default","protocol":"layer2","service":"metallb-system/test","ts":"2019-06-26T06:36:35.677084247Z"}
```

**Comment by danderson** [comment]
Fixed in 5cc6e237, just forgot to link it via the commit msg. Will be in next release.

**Comment by falfaro** [comment]
How does this work? I've updated to MetalLB 0.8.0 and I can't see any events published in any of my LoadBalanced Services.

**Comment by danderson** [comment]
There's a couple of issues with this, https://github.com/danderson/metallb/issues/455 and https://github.com/danderson/metallb/issues/456 . Together, they prevent publishing these events, and also the event itself contains no information :(

I'll release 0.8.1 later today with fixes.

**Comment by jmlogan** [comment]
Is this Event periodically published? Events are retained for 1h by default, and am not sure if this Event is published more frequently. I am trying to find the Speaker for a service that is rather old, and nothing is showing in the describe.

**Comment by fedepaol** [comment]
> Is this Event periodically published? Events are retained for 1h by default, and am not sure if this Event is published more frequently. I am trying to find the Speaker for a service that is rather old, and nothing is showing in the describe.

Hi @jmlogan , the event is published only when the speaker association is done ([here](https://github.com/metallb/metallb/blob/5d236989e61683daf1eaad00777b81ce7dd98c5d/speaker/main.go#L290)). If nothing changes in the service or in the list of endpoints, I believe the event is not produced (and in any case, I am sure it's not produced periodically).

**Comment by fedepaol** [comment]
Just to add more info, the association between service / node / lbip is avaliable as prometheus metric too : https://github.com/metallb/metallb/blob/5d236989e61683daf1eaad00777b81ce7dd98c5d/speaker/main.go#L284

**Comment by zhucan** [comment]
so, how to know the leader is? Is there doc for this?

**Comment by panpan0000** [comment]
> so, how to know the leader is? Is there doc for this?
1. find where your `LoadBalancer` type service , denote it's service AAA in namespace BBB
2.get its event kubectl -n BBB describe svc AAA
3. you will see event looks like 
```
  Normal  nodeAssigned  7m (x580 over 33d)  metallb-speaker  announcing from node "my-node3" with protocol "layer2"
  ```

**Comment by sathieu** [comment]
> Just to add more info, the association between service / node / lbip is avaliable as prometheus metric too :
> 
> https://github.com/metallb/metallb/blob/5d236989e61683daf1eaad00777b81ce7dd98c5d/speaker/main.go#L284

The metric is called `metallb_speaker_announced`. Thanks!

**Comment by fedepaol** [comment]
Please note we also have serviceL2Status now: https://github.com/metallb/metallb/blob/main/api/v1beta1/servicel2status_types.go
