### ISSUE TITLE
IP whitelisting

### ISSUE THREAD

**Issue by mikefaraponov** [danderson/metallb#431]
Feature
Add ability to whitelist IP addresses, CIDR, etc. for external coming requests

**Comment by paulwalko** [comment]
Could you explain a bit more? I'm not sure if you're talking about whitelisting IPs in a firewall sense to only access to certain ranges, or something like only allowing certain IPs to be allocated for certain services (see https://metallb.universe.tf/usage/).

**Comment by mikefaraponov** [comment]
I mean exactly and only firewall sense

**Comment by paulwalko** [comment]
Thanks, I was confused since this doesn't seem like something metallb should be responsible for doing since it is only a load balancer.
Instead, you should have a firewall service in front of metallb to filter external requests.

**Comment by mikefaraponov** [comment]
Sounds reasonable, thanks

**Comment by danderson** [comment]
This isn't possible with MetalLB's current design. MetalLB doesn't do any handling of the traffic once it reaches the nodes, it only helps direct traffic to the nodes. This would be a feature request for kube-proxy and/or the network addon you use, rather than MetalLB.
