### ISSUE TITLE
not able to find the proper utility for benchmark metallb

### ISSUE THREAD

**Issue by muralirm** [danderson/metallb#434]
we are using the metallb in 3 node cluster. 
[root@node1 layer2]# kubectl get nodes
NAME    STATUS   ROLES         AGE   VERSION
node1   Ready    master,node   25d   v1.13.5
node2   Ready    master,node   25d   v1.13.5
node3   Ready    node          25d   v1.13.5

my metallb controller and speaker is running 

metallb-controller-85bd848b55-7gsbd          1/1     Running   1          25d
metallb-speaker-bbcns                        1/1     Running   1          25d
metallb-speaker-r8scl                        1/1     Running   1          25d
metallb-speaker-vhp8b                        1/1     Running   1          25d

we want to benchmark the metallb, could you please recommended  any such tool to do this.

**Comment by danderson** [comment]
There are no recommendations, sorry. Use any network load generator you like.

In practice you'll be benchmarking kube-proxy, MetalLB is not involved in the transport of packets.
