### ISSUE TITLE
Build; Imports are still from go.universe.tf/metallb

### ISSUE THREAD

**Issue by uablrek** [danderson/metallb#440]
Imports are from the "old" location;

https://github.com/danderson/metallb/blob/7f5389259a394c622276d6e47bfd67145f97accc/controller/main.go#L23-L27

There are ways around this, e.g with links or clone from the new url but to the old location in $GOPATH.

Is there a prefered way?

I did a global sed and at least build with "go install" works fine.

**Comment by danderson** [comment]
Updated the go.universe.tf redirects to point to the new repo location. It should go live in ~5min and the build will work again.

**Comment by uablrek** [comment]
The old imports are still in the main branch;

https://github.com/danderson/metallb/blob/d2815bd2ad7cfe341581881a0dd0e9ea0dce4c00/controller/main.go#L23-L27

For instance `go test` fails;
```
controller > go test
main.go:23:2: use of internal package go.universe.tf/metallb/internal/allocator not allowed
service.go:24:2: use of internal package go.universe.tf/metallb/internal/allocator/k8salloc not allowed
main.go:24:2: use of internal package go.universe.tf/metallb/internal/config not allowed
main.go:25:2: use of internal package go.universe.tf/metallb/internal/k8s not allowed
main.go:26:2: use of internal package go.universe.tf/metallb/internal/logging not allowed
main.go:27:2: use of internal package go.universe.tf/metallb/internal/version not allowed
```

**Comment by uablrek** [comment]
This works;
```
GO111MODULE=on go test
```
I missed the module thing, sorry for bothering you.
