### ISSUE TITLE
[Feature] vlan tagging

### ISSUE THREAD

**Issue by Raboo** [danderson/metallb#445]
Hi,

I have a feature request, add support for vlan tagged VIPs.
i.e. The host is on a untagged vlan, and the VIP on another tagged vlan.

**Comment by danderson** [comment]
You should configure vlan interfaces on the k8s nodes to do this. The vlan interfaces don't need to have an IP configured, they just need to exist and be in state UP, then MetalLB can receive ARP requests from the vlan and handle them.

MetalLB isn't going to support this directly, we don't want to duplicate the work of the kernel.
