### ISSUE TITLE
[Website Bug] - Malformed image reference

### ISSUE THREAD

**Issue by eponerine** [danderson/metallb#449]
This is very low priority, but somewhat annoying.

Looks like references to clippy.svg in codeblocks are malformed. They're trying to resolve https://images/clippy.svg instead of the actual location https://metallb.universe.tf/images/clippy.svg

![image](https://user-images.githubusercontent.com/503974/61005926-232a1500-a337-11e9-8f4f-e52590c81a2d.png)

**Comment by danderson** [comment]
Huh, weird. I'll figure it out, thanks!

**Comment by danderson** [comment]
Looks like this has always been broken... Either that or hugo changed and somehow broke the theme's javascript.

Whatever, I hacked up the theme in 1c58a604 and the image loads now. Website will be happy when I ship the next MetalLB release.
