### ISSUE TITLE
MetalLB in ARP makes it hard to determine which speaker has been elected leader

### ISSUE THREAD

**Issue by teralype** [danderson/metallb#450]
I cannot find an easy way to determine which `speaker` pod of MetalLB when operating in ARP mode has been elected leader. Searching through the logs I can't find any event or some such:

```
kubectl -n metallb-system logs -l app=metallb --since=5m|grep -i arp
```

No events are shown in the controller, either.

The way I am currently finding the active leader is by pinging a VIP handled by MetalLB, looking at the ARP table to find the corresponding MAC address and then, and then iterate over all Kubernetes nodes to see which one owns that MAC address.

There must be an easier way to do this, but I can't seem to find any documentation. Any ideas?

Thanks!

**Comment by danderson** [comment]
Next release will have #430, which adds an event to the Service indicating which node is announcing.
