### ISSUE TITLE
speaker rbac missing event create/ patch rights

### ISSUE THREAD

**Issue by juliantaylor** [danderson/metallb#456]
metallb 0.8.0:

The speaker clusterrole does not contain rights to create and patch events in all namespaces:
https://github.com/danderson/metallb/blob/master/helm-chart/templates/rbac.yaml#L27

but the speaker tries to create events in the namespace of the services:
https://github.com/danderson/metallb/blob/master/speaker/main.go#L246

the config-watcher rbac role does contain event creation rights, but it is a rolebinding and this does not necessarily apply the to namespace of the service. Also it is missing the patch right.

**Comment by danderson** [comment]
Thanks for both your bug reports! I'll get these fixed and 0.8.1 released later today.
