### ISSUE TITLE
stable/metallb chart not updated

### ISSUE THREAD

**Issue by tomhur** [danderson/metallb#459]
Documentation says to use helm stable/metallb (when using helm) but that chart is not updated to use 0.8 version of metallb as https://github.com/danderson/metallb/tree/v0.8/helm-chart is.

**Comment by danderson** [comment]
Yup, updating the helm chart takes multiple days due to code review lag. In this case it'll take even longer because I forgot to submit the PR :).

I'll send the PR now. At some point we should move to hosting our own repo on hub.helm.sh, to simplify this.

**Comment by danderson** [comment]
PR submitted upstream: https://github.com/helm/charts/pull/15910

**Comment by danderson** [comment]
Fixed, helm upstream is 0.8.1.
