### ISSUE TITLE
High-res logo

### ISSUE THREAD

**Issue by dankohn** [danderson/metallb#463]
It could you provide the SVG, EPS, or AI of your logo https://metallb.universe.tf/images/logo.png we can add you to the Service Proxy section of https://landscape.cncf.io/.

**Comment by danderson** [comment]
Wish I could :(. The logo is a public domain logo that I tweaked in gimp a little (as you can tell from the subtle background color mismatch). I'd have to remake the logo in inkscape... Which would be a great thing to have, but not something I've had time to do so far.

**Comment by dankohn** [comment]
We'd be happy to recreate it for you, if you'd like. Are the flecks intentional? Also, we have a rule against reversed logos. (See https://github.com/cncf/landscape#logos). Want to give any more guidance and then I'll ask @alexcontini to give it a go.

**Comment by dankohn** [comment]
Could you please add the gimp file to the repo?

**Comment by dankohn** [comment]
[metallb.svg.zip](https://github.com/danderson/metallb/files/3516344/metallb.svg.zip)

Zipped because GitHub doesn't allow SVGs. Can you say what you'd like us to change in the logo (note that we don't support reversed logos). https://github.com/cncf/landscape#logos

**Comment by danderson** [comment]
Apologies for the delayed response! If you'd like to do some cleanup, I certainly wouldn't say no! That said, don't spend too much time on it either, I got a logo way back when because it seemed like the thing to do, I don't attach much value to the precise form :)

To your question, the flecks are not intentional, they're just a reflection of just how little time I spent tweaking the colors :D . The central white shape and white circle outline is the logo, the rest is notionally just transparent.

And no problem at all reversing the colors, I only went with white because it fit better against the background I was aiming for at the time.

Thank you!

**Comment by dankohn** [comment]
We're happy to do one more revision for you, if you'd like. Different color? Something else? Or, can we just go with this one?

**Comment by dankohn** [comment]
Ping. Can you say which color we should use if not that blue? Recall that the goal is to add MetalLB here: https://landscape.cncf.io/category=service-proxy&format=card-mode&grouping=category

**Comment by danderson** [comment]
Sorry, thought I'd responded. The logo exactly as-is is fine, please go ahead with that. And thanks again for making it good!

**Comment by dankohn** [comment]
And here you go: https://landscape.cncf.io/category=service-proxy&format=card-mode&grouping=category&selected=metal-lb

**Comment by dankohn** [comment]
Rather than have the landscape continue to use the cached data (which is what it will do since you deleted the Crunchbase data), I reverted my commit adding MetalLB to the landscape. If you're OK with MetalLB showing as a private organization or non-profit, I will add it back.

**Comment by danderson** [comment]
Sigh, I didn't think there'd be such a hard dependency on Crunchbase. Apologies for the churn. I put a profile back, have at it :(

**Comment by dankohn** [comment]
I understand the Crunchbase dependency seems odd, but it's generated a lot of value to have a unique URL for each organization and an independent, moderated source for tracking subsidiaries and such. https://landscape.cncf.io/category=service-proxy&format=card-mode&grouping=category&selected=metal-lb is back again.

**Comment by danderson** [comment]
Wouldn't want to get in the way of generating value! Thanks for the logo, and for getting MetalLB into the landscape.
