### ISSUE TITLE
metalb ping lost package

### ISSUE THREAD

**Issue by ruanshudong** [danderson/metallb#469]
i set up the k8s and metalb, version:
k8s: 1.14
metalb:0.8.1

metalb config:
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.16.124.10-172.16.124.50

kubectl -n ranchervm-system get svc/frontend:

NAME       TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
frontend   LoadBalancer   10.43.79.168   172.16.124.10   80:31218/TCP   48m

it seems metalb is working fine, but when i ping the ip:
[root@harbor rancherInstall]# ping 172.16.124.10
PING 172.16.124.10 (172.16.124.10) 56(84) bytes of data.
From 172.16.124.203 icmp_seq=2 Redirect HostFrom 172.16.124.203: icmp_seq=2 Redirect Host(New nexthop: 172.16.124.10)
From 172.16.124.203 icmp_seq=3 Redirect HostFrom 172.16.124.203: icmp_seq=3 Redirect Host(New nexthop: 172.16.124.10)
From 172.16.124.203 icmp_seq=4 Redirect HostFrom 172.16.124.203: icmp_seq=4 Redirect Host(New nexthop: 172.16.124.10)
From 172.16.124.203 icmp_seq=5 Destination Host Unreachable
From 172.16.124.203 icmp_seq=6 Destination Host Unreachable
From 172.16.124.203 icmp_seq=7 Destination Host Unreachable
From 172.16.124.203 icmp_seq=8 Destination Host Unreachable
From 172.16.124.203 icmp_seq=9 Destination Host Unreachable
From 172.16.124.203 icmp_seq=10 Destination Host Unreachable

seems lost packet, why?

**Comment by danderson** [comment]
MetalLB depends on kube-proxy for packet routing, and kube-proxy doesn't handle ICMP for services. Only the protocol+port specified in the Service object is reachable.

**Comment by champtar** [comment]
With kube-proxy ipvs, the service IP is configured on the ipvs interface, so the node respond to ping if I remember correctly.

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
