### ISSUE TITLE
Deployment should also come with tolerations

### ISSUE THREAD

**Issue by zerkms** [danderson/metallb#472]
Recently `tolerations` for the `DaemonSet` were added (https://github.com/danderson/metallb/commit/8b239b0d05ac94450f8a82324373a7b16390f7b5), but not to the `Deployment`.

**Comment by danderson** [comment]
Thanks for the report!

Hmm, I didn't really think about the controller. The speaker _must_ run on master nodes to serve LBs for pods on those nodes. The controller doesn't have to. Is that a problem, consuming precious master resources by default?

Unfortunately this is another case where it's difficult to provide a universal configuration :/

**Comment by zerkms** [comment]
Indeed speaker must, and I also now see your point that even though a controller _may_ it does not mean anybody would like to allow them to.

So now I see in this very case it's a matter of administrators' taste.

I personally will continue adding that toleration manually, and I suggest to close it then.
