### ISSUE TITLE
manifest for tag testgomake missing in repository metallb/controller

### ISSUE THREAD

**Issue by runningman84** [danderson/metallb#473]
We use flux to deploy our clusters. Flux is reporting this error every minute. Maybe you can fix the manifest for the testgomake image or just delete it:

ts=2019-09-03T12:39:55.436504901Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/metallb/controller auth={map[]} warn="manifest for tag testgomake missing in repository metallb/controller" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"

**Comment by danderson** [comment]
I don't understand what Flux is trying to say here. I searched Docker Hub and git for `testgomake`, and I didn't find any matches. So AFAICT so far, it's Flux that needs to be fixed, not metallb.

Happy to look again if you can point me at exactly what is making Flux angry.

**Comment by runningman84** [comment]
https://github.com/fluxcd/flux/issues/2517#issuecomment-542196756

"It is quite likely that the DockerHub UI filters out the image because the manifest is corrupt, while it is still accessible (and listed as a tag) for Docker API calls."

Can you take care of this?

**Comment by brokenjacobs** [comment]
Still an issue

**Comment by an-tex** [comment]
@danderson . There are more details in the comments to the issue in the flux repository, specifically 
- [testgomake tag exists for the metallb/controller](https://github.com/fluxcd/flux/issues/2517#issuecomment-551517645)
- [has no manifest associated to it](https://github.com/fluxcd/flux/issues/2517#issuecomment-551528953)
- [how to fix it](https://github.com/fluxcd/flux/issues/2517#issuecomment-551871688)
