### ISSUE TITLE
Feature request: Haproxy or generic api operation mode.

### ISSUE THREAD

**Issue by skyscooby** [danderson/metallb#480]
A lot of the legwork you have already done in managing IP pools, watching the kube API for LB events etc.. Perhaps MetalLB could expand to include a mode that reachs out to API / webhook endpoints with the Loadbalancer CRUD events?.. This would need to send the necessary action along with the allocated IP and desired configuration..

For example to have a haproxy mode that could talk to their data plane api.. https://www.haproxy.com/blog/new-haproxy-data-plane-api/ as an alternative to using L2 mode this would provide an actual load balancing solution without getting into BGP routing and could likely be implemented in a fully graceful manner

**Comment by danderson** [comment]
Nope, sorry. MetalLB is already complex enough to support without arbitrary hooks into external systems. I agree it would enable cool things, but with a single maintainer it's not tractable to open up such a large can of worms.
