### ISSUE TITLE
CIDR assign wrong initial IP

### ISSUE THREAD

**Issue by rptl** [danderson/metallb#483]
Assigning wrong initial IP, as outline below:

Version: 
MetalLB: 0.8.1
K8S: v1.15.0
weave: 2.5.2

Configuration: 
data: 
  config: | 
    address-pools: 
    - name: pool1 
      protocol: layer2 
      addresses: 
      - 192.168.10.0/23

NAME            TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
service/app1    LoadBalancer   10.101.200.12   **192.168.10.0**   80:32446/TCP   5m27s
service/app12   LoadBalancer   10.97.108.55    192.168.10.1   80:32147/TCP   7s

**Comment by danderson** [comment]
192.168.10.0 is a valid IP address in the CIDR you provided. MetalLB has no idea how the provided CIDRs map to ethernet network and broadcast addresses (usually the CIDR is a subset of the full L2 network). If you don't want those addresses to be used, use range notation in the config: `192.168.10.1-192.168.11.254`.

**Comment by rptl** [comment]
By Using that range you have provided, would 192.168.11.0 also be assgined?
