### ISSUE TITLE
speaker assignment is not reliable with multiple subnets

### ISSUE THREAD

**Issue by CoRfr** [danderson/metallb#484]
I was not able to find anything related to this in other issues, and I apologize if that was already raised.

I have a cluster where nodes are spread over 2 VLANs:
- 10.1.60.0/24 (most nodes)
- 10.1.4.0/24 (few nodes)

I gave a range of IP to metallb in the 10.1.60.0/24 subnet: 10.1.60.200-10.1.60.240 in layer 2 mode.

It worked fine until I started rebooting some nodes on the 10.1.60.0/24 subnet, then it started not being able to route IP assigned to metallb.

Looking a bit more into it, it appears that metallb only considers replying to ARPs from nodes where there are service endpoints. Since I didn't had any restriction on where my pods where running, some pods would run on nodes with 10.1.4.0/24 IPs.

My understanding is that in some cases, nodes in the 10.1.4.0/24 range would 'win' the right to speak ARPs, but the problem is that they never receive ARPs for the metallb range since they are not on that subnet.

As a workaround, I ended up restricting where pods that are exposed using metallb IPs can run. If all the endpoints are on nodes that are in the 10.1.60.0/24 it seems that everything is working fine.

**Comment by danderson** [comment]
Yup, this is by design. In L2 mode MetalLB assumes a completely flat network topology, where every node is equal. ARP is really not suitable for complex network topologies, you should use BGP mode for this. Sorry.

It's unlikely that I will fix this, so I'm going to close the bug. It simply adds too much complexity to layer2 mode to support these kinds of topologies.

**Comment by callicles** [comment]
@CoRfr Hi! I am facing the exact same issue, how did you restrict the pods on which metallb can speak?

**Comment by CoRfr** [comment]
Hey @callicles , I ended up assigning a `loadbalancer: "true"` label to all the nodes in the subnet that I want to use metallb on.
On the workload side, I have:
```
      nodeSelector:
        loadbalancer: "true"
```
for all the pods that I want to expose with an external IP.

Most of my services are webservices though, so I use traefik as an ingress controller (which has the above node selection restriction), but I don't need the restriction for the services and pods served using ingress because they only need cluster IPs, not external IPs.

So it's not too problematic in the end, but I was a bit surprised when I discovered the limitation.

**Comment by MrZXR** [comment]
> Yup, this is by design. In L2 mode MetalLB assumes a completely flat network topology, where every node is equal. ARP is really not suitable for complex network topologies, you should use BGP mode for this. Sorry.
> 
> It's unlikely that I will fix this, so I'm going to close the bug. It simply adds too much complexity to layer2 mode to support these kinds of topologies.

Hi !
I am trying to use cilium tunnel mode + MetalLB L2 mode with multiple subnets, will this work properly?

**Comment by MrZXR** [comment]
> > > Yup, this is by design. In L2 mode MetalLB assumes a completely flat network topology, where every node is equal. ARP is really not suitable for complex network topologies, you should use BGP mode for this. Sorry.
> > > It's unlikely that I will fix this, so I'm going to close the bug. It simply adds too much complexity to layer2 mode to support these kinds of topologies.
> > 
> > 
> > Hi ! I am trying to use cilium tunnel mode + MetalLB L2 mode with multiple subnets, will this work properly?
> 
> If all the nodes live in multiple subnets and there's no overlap between them, it should work. If you have different nodes belonging to different subnets, you can use the node selector in L2Advertisement. In general, please re ad the docs :P

Thank you very much for your reply! sorry to bother you. 
I googled "metallb" and "multiple subnets" before I read the documentation, and find this issue.

In Configuration-> Advanced L2 configuration, I found the configurations of multiple subnets, will deploy metallb in my cluster :)

Thanks again!

**Comment by fedepaol** [comment]
Glad to hear it helped!
