### ISSUE TITLE
MetalLB with Openstack floatingIPs

### ISSUE THREAD

**Issue by raonadeem** [danderson/metallb#486]
I have brought up a kubernetes cluster in openstack Virtual Machines and want to use metallb for kubernetes services using floating IPs pool.
Is there any way I can assign floating IP pool for metallb?
I don't want to use the openstack LBaaS or octavia for this scenario.

**Comment by danderson** [comment]
No. MetalLB works on OpenStack (see https://metallb.universe.tf/installation/clouds/#metallb-on-openstack for caveats), but doesn't integrate with OpenStack at all. When you deploy MetalLB on OpenStack, MetalLB is not aware that OpenStack exists, and OpenStack is not aware that MetalLB exists.

I have no plans to change this, as MetalLB's goal is to use standard network protocols to expose load-balancers, not private APIs of various cloud platforms.

**Comment by pfisterer** [comment]
@raonadeem I had this requirement, too. I've created an Ansible playbook that works for me: https://github.com/pfisterer/edsc-microk8s-playbook.

**Comment by kprasad99** [comment]
@pfisterer , In your case you are directly bring up VMs on external network right? Can we achieve this using private network?

**Comment by pfisterer** [comment]
@kprasad99 Yes, that's correct. 

I've tried using a private network. This has the major disadvantage that MetalLB "sees" the internal IP, which is then advertised to other components. Since I'm using external-dns, this provides the wrong IP for the "DNS name <-> IP" mapping.

Using the external network directly provides the correct, external IP. I haven't found any way to work around this problem with a private network.

**Comment by hetii** [comment]
@pfisterer In private mode do you attach your floating ip to some of the instance?
In my case I have just one floating ip, so I cannot use external network to handle my nodes.

**Comment by pfisterer** [comment]
@hetii No sure if I'm understanding you correctly. What do you mean by private mode?
 
In my case, I have a single node directly attached to an external network providing public IPs.

**Comment by deba10106** [comment]
could anyone guide me on this issue? We have a requirement to urgently solve this. I'm kind of stuck here.

**Comment by bnicolae86** [comment]
> could anyone guide me on this issue? We have a requirement to urgently solve this. I'm kind of stuck here.

 I managed to use floating ip with metallb. I created an openstack dummy port in the private network  and associated a FIP to it. The port wasn't attached to any instance. Then I deployed metallb and instructed to create the VIP with the private ip of the dummy port created before. The dummy port appear as DOWN but the traffic is forwarded from the FIP to metallb private IP .

**Comment by deba10106** [comment]
So, you use neutron port-create command?

**Comment by bnicolae86** [comment]
> So, you use neutron port-create command?

In fact I'm relying on terraform to do that. 

![image](https://user-images.githubusercontent.com/54812815/192973273-9db6d829-143f-4978-8959-eddcbd9fe5db.png)

After the port is created on Openstack, metallb will create the LB with the same IP. As you can see I'm using **var.kube_vip_ip** in both places.

![image](https://user-images.githubusercontent.com/54812815/192974268-b069fafa-8823-4e06-9b70-0a04e1206f11.png)

**Comment by eoinfennessy** [comment]
@bnicolae86 Using Terraform, I've followed what you've done here to associate floating IPs with fixed IP dummy ports on a private network. I'm getting timeouts trying to hit the floating IP associated with the LoadBalancer service's external IP (one of the dummy ports).

I've disabled port security on the private network (all instances and dummy ports), and "Binding: VNIC Type" of each dummy port is set to normal. Is there any other configuration you can think of that I may be missing? Did you have to configure port forwarding between floating IPs and private IPs (I haven't)?

Any help you could offer would be greatly appreciated!

**Comment by bnicolae86** [comment]
@eoinfennessy you can take a look at my manifest [https://justpaste.it/2zjoc](url) 
I remember that I had similar issues when the metallb VIP was created on a worker node. then I configured metallb only on control nodes and it was ok.

**Comment by eoinfennessy** [comment]
@bnicolae86 Thank you so much! I'm not using Helm to install MetalLB, but I will try to see if I can configure it to only use control plane nodes for the VIP. Do you happen to still have the Terraform script you used to create all the infrastructure? Also, do you remember if you needed to configure floating IP port forwarding to the dummy IP addresses?

**Comment by jacobdanovitch** [comment]
I've made this work on worker (/all) nodes without disabling port security. You create the dummy port and then add its fixed IP to the allowed-addresses on the ports for each node in your cluster. You can do this using the Openstack CLI with something like:

```shell
openstack port set $CLUSTER_NODE_PORT_ID --allowed-address ip_address=$(openstack port show $DUMMY_PORT_ID -c 'fixed_ips' -f json | jq -r '.fixed_ips[0].ip_address') 
```

Using Terraform (pseudocode from another project - may not work OOB):

```terraform
resource "openstack_networking_port_v2" "metallb" {
  count = var.num_lb_ips
  name               = "metallb-port-${count.index}"
  network_id         = var.network_id
  security_group_ids = var.sec_groups
  dns_name           = "metallb-${count.index}.k8s" # you can set a domain name for your load balancer if you want
}

resource "openstack_networking_port_v2" "cluster-node" {
  count = var.num_cluster_nodes
  name                  = "${var.name}-port"
  network_id            = var.network_id
  security_group_ids    = var.sec_groups 
  dynamic "allowed_address_pairs" {
    for_each = toset(flatten(openstack_networking_port_v2.metallb[*].all_fixed_ips))
    content {
      ip_address = allowed_address_pairs.value
    }
  }
}

resource "openstack_compute_instance_v2" "cluster-node" {
  count = var.num_cluster_nodes
  name        = "${var.cluster_name}-${count.index}"
  image_name  = var.image
  flavor_name = var.flavor
  key_pair    = var.keypair_name
  user_data   = var.user_data
  network {
    port = openstack_networking_port_v2.cluster-nodes[count.index].id
  }
}
```
I haven't tried this in a while with MetalLB but I was using it at one point and I currently have it running with kube-vip for an HA control plane. It shouldn't be that difficult to put together an operator for this but I haven't had the time.

**Comment by eoinfennessy** [comment]
@jacobdanovitch Thank you so much for your help! I will try using allowed address pairs instead of disabling port security across the private network. Can you please tell me how you were able to get traffic forwarded from a floating IP to a dummy port? Is it just a matter of associating the floating IP with the dummy port, or are extra steps necessary such as setting up port forwarding or changing VNIC binding types for ports?

**Comment by jacobdanovitch** [comment]
> @jacobdanovitch Thank you so much for your help! I will try using allowed address pairs instead of disabling port security across the private network. Can you please tell me how you were able to get traffic forwarded from a floating IP to a dummy port? Is it just a matter of associating the floating IP with the dummy port, or are extra steps necessary such as setting up port forwarding or changing VNIC binding types for ports?

I actually haven't tried attaching floating IPs as we're using Cloudflare Tunnels for external access, but I don't see why it would require anything more than simply associating the floating IP to the dummy port and ensuring the proper rules for whatever security group is attached to both your dummy and cluster node ports (e.g., allow 80/443 from 0.0.0.0/0). 

This should work using the dummy port IP for MetalLB, but I'm not sure if it would still work if you assigned the floating IP to MetalLB, which means Kubernetes will only be aware of the internal IP and not the floating one (in case you want to use ExternalDNS or anything).  I think it _should_ still work if you assign the floating IP to MetalLB (that seems to be what [this](https://medium.com/@nuriel_25979/virtual-ip-with-openstack-neutron-dd9378a48bdf) blog post does with `keepalived`) but I haven't tested it. 

I've never needed to touch the VNIC bindings but I'm not sure if that varies between Openstack providers.

**Comment by eoinfennessy** [comment]
@jacobdanovitch Very helpful reply and blog post. Thank you. I'm hoping to allocate a pool of dummy IPs for MetalLB to hand out and then associate these with floating IPs. I then plan to configure A records on my domain name server to point to the external (floating) IPs so k8s should(?) not need to be aware of the external floating IPs. I'll try using allowed address pairs instead of disabling port security and will post my config here if I can get something working.

**Comment by bnicolae86** [comment]
@eoinfennessy no extra steps are necessary. just the allow address pair set up on the ports. 

`resource "openstack_networking_port_v2" "rke2-node-ports" {
  count 		= var.rke2_node_number
  name 			= "rke2-node-port-${count.index+1}"
  network_id 		= data.openstack_networking_network_v2.rke2-network.id
  admin_state_up 	= "true"
  fixed_ip {
    subnet_id = data.openstack_networking_subnet_v2.rke2-subnet.id
  }
  allowed_address_pairs {
    ip_address = data.openstack_networking_subnet_v2.rke2-subnet.cidr
  }
}
`

**Comment by Alixpat** [comment]
This works well for me on a microk8s and OpenStack cluster. Have you considered the L2Advertisement?
