### ISSUE TITLE
Limitation to 1 MetalLB system per layer 2 network?

### ISSUE THREAD

**Issue by mjpitz** [danderson/metallb#519]
Not really looking for troubleshooting instructions here, but I wanted to talk through some behavior that I'm seeing on my home network. I have two k3s clusters set up. Both of them are connected to my home network over wifi. When I install MetalLB on one, everything seems to work fine for some time. But as soon as I install MetalLB on the other, everything seems to break down. Each MetalLB system uses a unique range of IPs so they don't overlap and each node is assigned a static IP.

In reading the Layer 2 documentation, I didn't see any mention about this kind of limitation. I'm curious is this a known limitation or more likely something odd with my setup?

**Comment by danderson** [comment]
There's no such limitation. As long as the clusters are using different sets of IPs for services, they should not be interfering with each other. So, there's likely something amiss in your setup (off the top of my head: check that the IP ranges are indeed not overlapping, and also not overlapping with DHCP ranges; and check for some kind of spoofing/port security on your switches, if you have switches with that functionality).

**Comment by mjpitz** [comment]
Interesting. I bet thats it based on what I'm reading. Thanks for the help!
